/*
 * This source file was generated by the Gradle 'init' task
 */
package zoro.terminal;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

import zoro.terminal.buffer.TerminalBuffer;
import zoro.terminal.controller.TerminalKeyHandler;
import zoro.terminal.controller.TerminalMouseHandler;
import zoro.terminal.ui.TerminalView;

public class App {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            // 80 columns, 24 rows, 1000 lines scrollback
            TerminalBuffer buffer = new TerminalBuffer(80, 24, 1000);
            TerminalView view = new TerminalView(buffer);
            
            TerminalKeyHandler keyHandler = new TerminalKeyHandler(buffer, view);
            TerminalMouseHandler mouseHandler = new TerminalMouseHandler(buffer, view);
            
            view.addKeyListener(keyHandler);
            view.addMouseWheelListener(mouseHandler);
            view.addMouseListener(mouseHandler);
            view.addMouseMotionListener(mouseHandler);

            JFrame frame = new JFrame("Zoro Terminal");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.add(view);
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
            
            view.requestFocusInWindow();
        });
    }
}
