/*
 * This source file was generated by the Gradle 'init' task
 */
package zoro.terminal;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appTests() {
        // App class tests to be added here later
    }
}
